name: SunBlastTierTagger
version: '2.0'
main: me.rizzener.sunblasttiertagger.SunBlastTierTagger
api-version: '1.16'
load: STARTUP
author: Rizzener
softdepend: [PlaceholderAPI]
commands:
  tiers:
    aliases: [sbtiers]